server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://rm-bp1r2r1h041zt4768co.mysql.rds.aliyuncs.com:3306/anno?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: None19970130

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml

token:
  # 1000 * 60 * 60 * 24 * 3 \u4E09\u5929
  expireTime: 259200000
  # \u90E8\u7F72\u4E0A\u7EBF\u52A1\u5FC5\u4FEE\u6539\u6B64\u914D\u7F6E\uFF0C\u5426\u5219\u65E0\u6CD5\u4FDD\u8BC1token\u5B89\u5168\u6027
  secretKey: abcdefghijklmnopqrstuvwxyz
